site_name: d6Engine
site_author: Chuck Mo
copyright: GPLv3
repo_url: https://gitlab.com/thechuckmo/d6engine/
edit_uri: blob/master/docs/
google_analytics: [UA-138667896-1, d6engine.org]

#pages:
#   - Install: guides/install.md
#   - DevSetup: guides/devsetup.md
#   - Examples:   guides/examples.md

theme:
        name: cluster

extra:
        fa_logo: 'fa-dice-one'
    #prev_next_enabled: False
    #nav_right: ['Install', 'DevSetup', 'Examples']
    #hidden: ['Home']

