[metadata]
name = 'd6engine'
version = '0.0.1'
description = ''
author = 'Chuck Mo'
author_email = 'chuck@moosejudge.com'
license = 'MIT/Apache-2.0'
url = 'https://gitlab.com/thechuckmo/d6engine'

[requires]
python_version = ['3.6', 'pypy3']

[build-system]
requires = ['setuptools', 'wheel']

[tool.hatch.commands]
prerelease = 'hatch build'
