[metadata]
name = 'd6engine'
version = '0.0.1'
description = 'D6Engine'
author = 'Chuck Mo'
author_email = 'chuck@moosejudge.com'
license = 'GPLv3'
url = 'https://gitlab.com/thechuckmo/d6engine'

[requires]
python_version = ['3.6', '3.7']

[build-system]
requires = ['setuptools', 'wheel']

[tool.hatch.commands]
prerelease = 'hatch build'
